---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: docs-puller-secret
  namespace: homelab
spec:
  encryptedData:
    GITHUB_TOKEN: AgCt3rOLerF3S4l7oUtjZztaKzNAjuDAAMoeb2mdIRAG6OaYbSwGvyHV/UGavrVsSMDUPGGt6qP2zhorT0AeMmmTHD0mV2jjIfZXg0nBEcYCtlnAzI3pkAhKE9JB5BmKSaQBC2dOCU/tzYuz2tkfWiK2lJ7iM+ODQuLu+yQz0uCTATY5T5T9hh/SleSsOs9aPUPiQaBB1fWonRl0tE2TXHPKupnMMpOqgVxqenrmd7o+nuqnuJJE0Klgf5RQ4kiUEhD7utu8LuHrZ+GPhmB6881dUXCM6TfWpSzE97ZIwAFbEjW8eEfJ1sFv5eRnm+8BT3qozbCdEcWzS+kGT3CpRkgapQ/VKa1D1lMp5OSAzQMfHcgBRZC9VAoLPNGDo+ZGPgKLpY1xN2MXUEP3Ua+Plc/ZLjyxD9/qs00KK7X11nWFNgCkGF0GKXHz4HASJzUXu3RjAcUfBACe00KMAiUdj6z7Ol63xCHJ0BJhtZFSYGycpdoL/Tu4QmlvjI7sS9UDjJEacPsJ5OS9hcmqweANRDLVlLxkm42X6dW8/qnZ/7tpMf8Aeiv00ku4aqP9G4AXN/Jm5S3kHMGgQIrGBv50gJP7hLNUEjOz6ggztsLLofOBtbyi2avEORcQ8ShSQY2jnLAfiw3DBzXlV5+7xwUHcnvqiM+5vvyCfFS62Gq3xrWY7RXuWsvCFW5ntuVQ9+FJKje3JGxx5HC2OpyP35TavErG+xDIhnt1QVvKFSbHtEZrV4yyl5DCWpqA
  template:
    metadata:
      name: docs-puller-secret
      namespace: homelab
    type: Opaque
